src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuthorRepository")
 * @UniqueEntity(
 *  fields={"surname", "name", "midname"},
 *  message="validators.author.exists"
 * )
 */
class Author
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="validation.author.name")
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="validation.author.surname")
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="validation.author.midname")
     */
    private $midname;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Book", mappedBy="authors")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getMidname(): ?string
    {
        return $this->midname;
    }

    public function setMidname(string $midname): self
    {
        $this->midname = $midname;

        return $this;
    }

    // Special getter for full name with initials 
    public function getFullname(): ?string
    {
        return $this->surname . ' ' . 
            mb_substr($this->name, 0, 1) . '. ' . 
            mb_substr($this->midname, 0, 1) . '.';
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->contains($book)) {
            $this->books->removeElement($book);
            $book->removeAuthor($this);
        }

        return $this;
    }
}

src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('surname', TextType::class, [
                'label' => 'form.author.surname'
            ])
            ->add('name', TextType::class, [
                'label' => 'form.author.name'
            ])
            ->add('midname', TextType::class, [
                'label' => 'form.author.midname'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class AuthorController extends AbstractController
{
    /**
     * @Route("/author", name="author")
     */
    public function index()
    {
        $repo = $this->getDoctrine()->getRepository(Author::class);
        $authors = $repo->findAll();
        return $this->render('author/index.html.twig', [
            'authors' => $authors,
        ]);
    }

    /**
     * @Route("/author/create", name="author_create")
     */
    public function create(Request $request)
    {
        $author = new Author();
        $form = $this->createForm(AuthorType::class, $author)
            ->add('submit', SubmitType::class, [
                'label' => 'form.create'
            ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $author = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($author);
            $entityManager->flush();

            return $this->redirectToRoute('author');
        }
        
        return $this->render('form.html.twig', [
            'form' => $form->createView(),
            'title' => 'form.author.create'
        ]);
    }

    /**
     * @Route("/author/{id}", name="author_show")
     */
    public function show(Author $author)
    {
        return $this->render('author/show.html.twig', [
            'author' => $author
        ]);
    }

    /**
     * @Route("/author/{id}/edit", name="author_edit")
     */
    public function edit(Author $author, Request $request)
    {
        $form = $this->createForm(AuthorType::class, $author)
            ->add('submit', SubmitType::class, [
                'label' => 'form.update'
            ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('author');
        }
        
        return $this->render('form.html.twig', [
            'form' => $form->createView(),
            'title' => 'form.author.update'
        ]);
    }

    /**
     * @Route("/author/{id}/remove", name="author_remove")
     */
    public function remove(Author $author)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($author);
        $entityManager->flush();
        return $this->redirectToRoute('author');
    }
}

templates/author/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title|trans }}{% endblock %}

{% block body %}
<div class="card shadow mt--300">
    <div class="card-body">
        <h1>{{ title|trans }}</h1>

        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'site.author.list'|trans }}{% endblock %}

{% block body %}

<div class="card shadow mt--300">
    <table class="table table-hover table-striped mb-0">
        <thead class="text-center">
            <tr>
                <th>{{ 'site.author.fullname'|trans }}</th>
                <th>{{ 'site.author.books_count'|trans }}</th>
                <th>{{ 'site.author.actions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
            {% for author in authors %}
                <tr>
                    <td data-toggle="tooltip" data-placement="top" title="{{ author.surname }} {{ author.name }} {{ author.midname }}">
                        <a href="{{ path('author_show', {'id': author.id}) }}">{{ author.fullname }}</a>
                    </td>
                    <td>{{ author.books|length }}</td>
                    <td>
                        <a class="btn btn-sm btn-icon btn-2 btn-primary" href="{{ path('author_edit', {'id': author.id}) }}">
                            <i class="fa fa-edit"></i>
                        </a>
                        <a class="btn btn-sm btn-icon btn-2 btn-danger" href="{{ path('author_remove', {'id': author.id}) }}">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/author/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ author.fullname }}{% endblock %}

{% block body %}
    <div class="mt--300">
        <h1 class="display-2 text-white mb-5">{{ author.surname }} {{ author.name }} {{ author.midname }}</h1>
        {% include 'book/list.html.twig' with {'books': author.books} %}
    </div>
{% endblock %}